Repository johnshamoon/robotic-leader-follower, pull requests merged in 2019-03, with the labels that each got.

#29 Add tag recognition class
  experimental/opencv/tag_recognition.py
  src/tagrec.py
Labels: bugfix, enhancement

#28 Refactor Follower Class
  src/follower.py
Labels: enhancement

#33 Added function to lead
  src/leader.py
Labels: enhancement

#34 Added tag yaw
  src/tagrec.py
Labels: enhancement

#31 script to determine leader or follower functionality
  src/main.py
Labels: enhancement

#27 Added Script that can connect a bluetooth Xbox controller to the RPi
  src/bt_toggle.sh
Labels: enhancement

#35 Change follower to use yaw
  src/follower.py
Labels: enhancement

#40 create function to determine if Bluetooth joystick is connected
  src/main.py
Labels: enhancement

#42 Update Readme
  README.md
Labels: enhancement

#44 Leadercontrol
  src/leader.py
Labels: enhancement

#45 Stop Follower From Opening Second Camera Stream
  src/main.py
Labels: bugfix

#46 Tune Follower
  src/follower.py
Labels: enhancement

#47 Fix paths so we can run the files from any directory
  src/follower.py
  src/leader.py
Labels: enhancement

#41 Add Authors To Files
  experimental/opencv/camera_stream.py
  experimental/opencv/make_blob.py
  experimental/opencv/tag_recognition.py
  experimental/opencv/tag_visualization.py
  simulation/webots/controllers/follower_vehicle/Makefile
  simulation/webots/controllers/follower_vehicle/follower_vehicle.cpp
  simulation/webots/controllers/follower_vehicle/include/follower.hpp
  simulation/webots/controllers/follower_vehicle/src/follower.cpp
  simulation/webots/controllers/forward_collision_avoidance/Makefile
  simulation/webots/controllers/forward_collision_avoidance/forward_collision_avoidance.cpp
  simulation/webots/controllers/remote_control_car.py
  src/bt_toggle.sh
  src/follower.py
  src/inputcontroller.py
  src/leader.py
  src/main.py
  src/tagrec.py
Labels: enhancement

#43 Add Sphinx Documentation Scripts
  .gitignore
  docs/Makefile
  docs/conf.py
  docs/follower.rst
  docs/index.rst
  docs/inputcontroller.rst
  docs/leader.rst
  docs/main.rst
  docs/modules.rst
  docs/requirements.txt
  docs/tagrec.rst
  src/follower.py
  src/inputcontroller.py
  src/leader.py
  src/tagrec.py
Labels: enhancement

#49 Added documentation link to README
  README.md
Labels: enhancement

#51 Bugfix: Move follow docstring within function
  src/follower.py
Labels: bugfix

#53 Add leader and follower constants
  src/follower.py
  src/leader.py
Labels: enhancement
