Repository johnshamoon/robotic-leader-follower, pull requests merged in 2019-04, with the labels that each got.

#55 Changed set speed function to incorporate different accelerations
  src/leader.py
Labels: bugfix, enhancement

#58 Added GPL to Repo
  LICENSE
Labels: enhancement

#61 Fix InputController Button States
  src/inputcontroller.py
Labels: bugfix

#59 Update Follower to Use Dictionary
  src/follower.py
Labels: enhancement

#63 Fix bluetoothctl.py docstring
  src/bluetoothctl.py
Labels: bugfix

#37 Roleswapping
  experimental/role_swapping.py
Labels: experimental

#62 Integrated Jevois camera
  etc/videomappings.cfg
  src/tagrec.py
Labels: enhancement

#65 Add empty test directories
  test/camera/README.md
  test/follower/README.md
  test/inputcontroller/README.md
  test/leader/README.md
  test/tagrec/README.md
Labels: enhancement

#66 Remove reset camera from Follower
  src/follower.py
Labels: enhancement

#69 Stop the docs from sorting the contents
  docs/conf.py
Labels: bugfix

#71 Tagrec fixes
  src/tagrec.py
Labels: bugfix

#70 Parameterize opencv_to_wheels and add input validation
  src/follower.py
Labels: bugfix, enhancement

#68 Add parameter checking
  src/leader.py
Labels: bugfix

#76 Division by Zero Error Handling
  src/tagrec.py
Labels: bugfix

#74 Added functionality to bypass camera feed for testing
  src/tagrec.py
Labels: enhancement, testing

#78 Add test pictures
  test/res/tag_pictures/left_no_turn_12in.HEIC
  test/res/tag_pictures/left_no_turn_5in.HEIC
  test/res/tag_pictures/left_sharp_turn_left_12in.HEIC
  test/res/tag_pictures/left_sharp_turn_left_5in.HEIC
  test/res/tag_pictures/left_sharp_turn_right_12in.HEIC
  test/res/tag_pictures/left_sharp_turn_right_5in.HEIC
  test/res/tag_pictures/left_slight_turn_left_12in.HEIC
  test/res/tag_pictures/left_slight_turn_left_5in.HEIC
  test/res/tag_pictures/left_slight_turn_right_12in.HEIC
  test/res/tag_pictures/left_slight_turn_right_5in.HEIC
  test/res/tag_pictures/right_no_turn_12in.HEIC
  test/res/tag_pictures/right_no_turn_5in.HEIC
  test/res/tag_pictures/right_sharp_turn_left_12in.HEIC
  test/res/tag_pictures/right_sharp_turn_left_5in.HEIC
  test/res/tag_pictures/right_sharp_turn_right_12in.HEIC
  test/res/tag_pictures/right_sharp_turn_right_5in.HEIC
  test/res/tag_pictures/right_slight_turn_left_12in.HEIC
  test/res/tag_pictures/right_slight_turn_left_5in.HEIC
  test/res/tag_pictures/right_slight_turn_right_12in.HEIC
  test/res/tag_pictures/right_slight_turn_right_5in.HEIC
  test/res/tag_pictures/straight_no_turn_12in.HEIC
  test/res/tag_pictures/straight_no_turn_5in.HEIC
  test/res/tag_pictures/straight_sharp_turn_left_12in.HEIC
  test/res/tag_pictures/straight_sharp_turn_left_5in.HEIC
  test/res/tag_pictures/straight_sharp_turn_right_12in.HEIC
  test/res/tag_pictures/straight_sharp_turn_right_5in.HEIC
  test/res/tag_pictures/straight_slight_turn_left_12in.HEIC
  test/res/tag_pictures/straight_slight_turn_left_5in.HEIC
  test/res/tag_pictures/straight_slight_turn_right_12in.HEIC
  test/res/tag_pictures/straight_slight_turn_right_5in.HEIC
Labels: testing

#82 Make Main Testable
  docs/bluetoothctl.rst
  docs/index.rst
  docs/modules.rst
  experimental/bluetoothctl.py
  src/main.py
Labels: bugfix, enhancement

#83 Image resolution fix
  src/tagrec.py
Labels: bugfix

#84 Fixed brightness typo
  src/tagrec.py
Labels: bugfix

#80 Wrote tests for main.py class
  test/main/README.md
  test/main/main_test.py
Labels: testing

#38 Customcamera
  docs/camera.rst
  docs/conf.py
  docs/index.rst
  docs/modules.rst
  src/camera.py
  src/config
  src/follower.py
  src/leader.py
Labels: enhancement

#91 Tagrec tests
  test/res/tag_pictures/tag_center.jpg
  test/tagrec/README.md
  test/tagrec/tagrec_test.py
Labels: testing

#92 Improve following
  src/follower.py
  src/leader.py
Labels: bugfix, enhancement

#93 Follower testing
  src/follower.py
  test/follower/follower_test.py
Labels: bugfix, testing

#94 Add leader tests
  src/leader.py
  test/leader/README.md
  test/leader/leader_test.py
Labels: bugfix, testing

#95 Add script to run tests
  test/run_tests.sh
Labels: enhancement
